import { Race } from "@/types/race";

export const countries = {
  austria: {
    id: "austria",
    name: "Austria",
  },
  italy: {
    id: "italy",
    name: "Italy",
  },
  germany: {
    id: "germany",
    name: "Germany",
  },
  unitedKingdom: {
    id: "unitedKingdom",
    name: "United Kingdom",
  },
  switzerland: {
    id: "switzerland",
    name: "Switzerland",
  },
  unitedStates: {
    id: "unitedStates",
    name: "United States",
  },
  france: {
    id: "france",
    name: "France",
  },
  bahrain: {
    id: "bahrain",
    name: "Bahrain",
  },
  saudiArabia: {
    id: "saudiArabia",
    name: "Saudi Arabia",
  },
  australia: {
    id: "australia",
    name: "Australia",
  },
  japan: {
    id: "japan",
    name: "Japan",
  },
  china: {
    id: "china",
    name: "China",
  },
  monaco: {
    id: "monaco",
    name: "Monaco",
  },
  canada: {
    id: "canada",
    name: "Canada",
  },
  spain: {
    id: "spain",
    name: "Spain",
  },
  hungary: {
    id: "hungary",
    name: "Hungary",
  },
  belgium: {
    id: "belgium",
    name: "Belgium",
  },
  netherlands: {
    id: "netherlands",
    name: "Netherlands",
  },
  azerbaijan: {
    id: "azerbaijan",
    name: "Azerbaijan",
  },
  singapore: {
    id: "singapore",
    name: "Singapore",
  },
  mexico: {
    id: "mexico",
    name: "Mexico",
  },
  brazil: {
    id: "brazil",
    name: "Brazil",
  },
  qatar: {
    id: "qatar",
    name: "Qatar",
  },
  abuDhabi: {
    id: "abuDhabi",
    name: "Abu Dhabi",
  },
} as const;

export const teams = {
  redBull: {
    id: "redBull",
    name: "Red Bull",
    country: countries.austria,
  },
  ferrari: {
    id: "ferrari",
    name: "Ferrari",
    country: countries.italy,
  },
  mercedes: {
    id: "mercedes",
    name: "Mercedes",
    country: countries.germany,
  },
  mclaren: {
    id: "mclaren",
    name: "Mclaren",
    country: countries.unitedKingdom,
  },
  astonMartin: {
    id: "astonMartin",
    name: "Aston Martin",
    country: countries.unitedKingdom,
  },
  kickSauber: {
    id: "kickSauber",
    name: "Kick Sauber",
    country: countries.switzerland,
  },
  haas: {
    id: "haas",
    name: "Haas",
    country: countries.unitedStates,
  },
  rB: {
    id: "rB",
    name: "RB",
    country: countries.italy,
  },
  williams: {
    id: "williams",
    name: "Williams",
    country: countries.unitedKingdom,
  },
  alpine: {
    id: "alpine",
    name: "Alpine",
    country: countries.france,
  },
} as const;

export const drivers = {
  maxVerstappen: {
    id: "maxVerstappen",
    name: "Max Verstappen",
    // country: "",
    team: teams.redBull,
  },
  sergioPerez: {
    id: "sergioPerez",
    name: "Sergio Perez",
    // country: "",
    team: teams.redBull,
  },
  charlesLeclerc: {
    id: "charlesLeclerc",
    name: "Charles Leclerc",
    // country: "",
    team: teams.ferrari,
  },
  carlosSainz: {
    id: "carlosSainz",
    name: "Carlos Sainz",
    // country: "",
    team: teams.ferrari,
  },
  georgeRussell: {
    id: "georgeRussell",
    name: "George Russell",
    // country: "",
    team: teams.mercedes,
  },
  lewisHamilton: {
    id: "lewisHamilton",
    name: "Lewis Hamilton",
    // country: "",
    team: teams.mercedes,
  },
  landoNorris: {
    id: "landoNorris",
    name: "Lando Norris",
    // country: "",
    team: teams.mclaren,
  },
  oscarPiastri: {
    id: "oscarPiastri",
    name: "Oscar Piastri",
    // country: "",
    team: teams.mclaren,
  },
  fernandoAlonso: {
    id: "fernandoAlonso",
    name: "Fernando Alonso",
    // country: "",
    team: teams.astonMartin,
  },
  lanceStroll: {
    id: "lanceStroll",
    name: "Lance Stroll",
    // country: "",
    team: teams.astonMartin,
  },
  zhouGuanyu: {
    id: "zhouGuanyu",
    name: "Zhou Guanyu",
    // country: "",
    team: teams.kickSauber,
  },
  valtteriBottas: {
    id: "valtteriBottas",
    name: "Valtteri Bottas",
    // country: "",
    team: teams.kickSauber,
  },
  kevinMagnussen: {
    id: "kevinMagnussen",
    name: "Kevin Magnussen",
    // country: "",
    team: teams.haas,
  },
  nicoHulkenberg: {
    id: "nicoHulkenberg",
    name: "Nico Hulkenberg",
    // country: "",
    team: teams.haas,
  },
  danielRicciardo: {
    id: "danielRicciardo",
    name: "Daniel Ricciardo",
    // country: "",
    team: teams.rB,
  },
  yukiTsunoda: {
    id: "yukiTsunoda",
    name: "Yuki Tsunoda",
    // country: "",
    team: teams.rB,
  },
  alexanderAlbon: {
    id: "alexanderAlbon",
    name: "Alexander Albon",
    // country: "",
    team: teams.williams,
  },
  loganSargeant: {
    id: "loganSargeant",
    name: "Logan Sargeant",
    // country: "",
    team: teams.williams,
  },
  estebanOcon: {
    id: "estebanOcon",
    name: "Esteban Ocon",
    // country: "",
    team: teams.alpine,
  },
  pierreGasly: {
    id: "pierreGasly",
    name: "Pierre Gasly",
    // country: "",
    team: teams.alpine,
  },
};

export const races: Array<Race> = [
  {
    id: 1,
    name: "Bahrain Grand Prix",
    circuitName: "Bahrain International Circuit",
    date: new Date("2024-03-02"),
    country: countries.bahrain,
    status: "completed",
    result: {
      pole: drivers.maxVerstappen,
      first: drivers.maxVerstappen,
      last: drivers.loganSargeant,
      fastestLap: drivers.maxVerstappen,
      fastestPitStop: teams.ferrari,
    },
  },
  {
    id: 2,
    name: "Saudi Arabian Grand Prix",
    circuitName: "Jeddah Corniche Circuit",
    date: new Date("2024-03-09"),
    country: countries.saudiArabia,
    status: "inProgress",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 3,
    name: "Australian Grand Prix",
    circuitName: "Albert Park Circuit",
    date: new Date("2024-03-24"),
    country: countries.australia,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 4,
    name: "Japanese Grand Prix",
    circuitName: "Suzuka International Racing Course",
    date: new Date("2024-04-07"),
    country: countries.japan,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 5,
    name: "Chinese Grand Prix",
    circuitName: "Shanghai International Circuit",
    date: new Date("2024-04-21"),
    country: countries.china,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
    sprintResult: {
      pole: null,
      first: null,
    },
  },
  {
    id: 6,
    name: "Miami Grand Prix",
    circuitName: "Miami International Autodrome",
    date: new Date("2024-05-05"),
    country: countries.unitedStates,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
    sprintResult: {
      pole: null,
      first: null,
    },
  },
  {
    id: 7,
    name: "Emilia Romagna Grand Prix",
    circuitName: "Imola Circuit",
    date: new Date("2024-05-19"),
    country: countries.italy,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 8,
    name: "Monaco Grand Prix",
    circuitName: "Circuit de Monaco",
    date: new Date("2024-05-26"),
    country: countries.monaco,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 9,
    name: "Canadian Grand Prix",
    circuitName: "Circuit Gilles Villeneuve",
    date: new Date("2024-06-09"),
    country: countries.canada,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 10,
    name: "Spanish Grand Prix",
    circuitName: "Circuit de Barcelona-Catalunya",
    date: new Date("2024-06-23"),
    country: countries.spain,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 11,
    name: "Austrian Grand Prix",
    circuitName: "Red Bull Ring",
    date: new Date("2024-06-30"),
    country: countries.austria,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
    sprintResult: {
      pole: null,
      first: null,
    },
  },
  {
    id: 12,
    name: "British Grand Prix",
    circuitName: "Silverstone Circuit",
    date: new Date("2024-07-07"),
    country: countries.unitedKingdom,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 13,
    name: "Hungarian Grand Prix",
    circuitName: "Hungaroring",
    date: new Date("2024-07-21"),
    country: countries.hungary,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 14,
    name: "Belgian Grand Prix",
    circuitName: "Circuit de Spa-Francorchamps",
    date: new Date("2024-07-28"),
    country: countries.belgium,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 15,
    name: "Dutch Grand Prix",
    circuitName: "Circuit Zandvoort",
    date: new Date("2024-08-25"),
    country: countries.netherlands,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 16,
    name: "Italian Grand Prix",
    circuitName: "Monza Circuit",
    date: new Date("2024-09-01"),
    country: countries.italy,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 17,
    name: "Azerbaijan Grand Prix",
    circuitName: "Baku City Circuit",
    date: new Date("2024-09-15"),
    country: countries.azerbaijan,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 18,
    name: "Singapore Grand Prix",
    circuitName: "Marina Bay Street Circuit",
    date: new Date("2024-09-22"),
    country: countries.singapore,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 19,
    name: "United States Grand Prix",
    circuitName: "Circuit of the Americas",
    date: new Date("2024-10-20"),
    country: countries.unitedStates,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
    sprintResult: {
      pole: null,
      first: null,
    },
  },
  {
    id: 20,
    name: "Mexico City Grand Prix",
    circuitName: "Autódromo Hermanos Rodríguez",
    date: new Date("2024-10-27"),
    country: countries.mexico,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 21,
    name: "São Paulo Grand Prix",
    circuitName: "Interlagos Circuit",
    date: new Date("2024-11-03"),
    country: countries.brazil,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
    sprintResult: {
      pole: null,
      first: null,
    },
  },
  {
    id: 22,
    name: "Las Vegas Grand Prix",
    circuitName: "Las Vegas Strip Circuit",
    date: new Date("2024-11-023"),
    country: countries.unitedStates,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
  {
    id: 23,
    name: "Qatar Grand Prix",
    circuitName: "Lusail International Circuit",
    date: new Date("2024-12-01"),
    country: countries.qatar,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
    sprintResult: {
      pole: null,
      first: null,
    },
  },
  {
    id: 24,
    name: "Abu Dhabi Grand Prix",
    circuitName: "Yas Marina Circuit",
    date: new Date("2024-12-08"),
    country: countries.abuDhabi,
    status: "upcoming",
    result: {
      pole: null,
      first: null,
      last: null,
      fastestLap: null,
      fastestPitStop: null,
    },
  },
] as const;
